apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: shreekulkarni/assignment:0.2
        ports:
        - containerPort: 80 
