apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas : 2
  selector:
    matchLabels:
      app: myapp
template:
    metadata:
      name: demo-dep
      labels:
        app: myapp      
    spec:
      containers:
      - name: assignment-container
        image: assignment:0.1
        ports:
        - containerPort: 80
